import part1 from '../Assets/CSMlogo2.png';
import part2 from '../Assets/Craiova.png';

export const cmdata=[
    {
        Runda : 1,
        DataMeci: '20.11.2022',
        OraMeci: '10:00',
        NumeEchipa: 'Speranta Bucuresti',
        NumeEchipa2: 'Juventus Timisoara',
        img1: part1,
        img2: part2,
        cifra1: 0,
        cifra2: 1,
        locMeci: 'Acasa',
        tipcampionat: 'Cupa Romaniei',

    },
    {
        Runda : 2,
        DataMeci: '20.11.2022',
        OraMeci: '10:00',
        NumeEchipa: 'Speranta Bucuresti',
        NumeEchipa2: 'Juventus Timisoara',
        img1: part1,
        img2: part2,
        cifra1: 0,
        cifra2: 1,
        locMeci: 'Acasa ',
        tipcampionat: 'Super Cupa Romaniei',

    },
    {
        Runda : 3,
        DataMeci: '20.11.2022',
        OraMeci: '10:00',
        NumeEchipa: 'Speranta Bucuresti',
        NumeEchipa2: 'Juventus Timisoara',
        img1: part1,
        img2: part2,
        cifra1: 0,
        cifra2: 1,
        locMeci: 'Acasa ',
        tipcampionat: 'Turneu Promovare A1M',

    },
    {
        Runda : 1,
        DataMeci: '20.11.2022',
        OraMeci: '10:00',
        NumeEchipa: 'Speranta Bucuresti',
        NumeEchipa2: 'Juventus Timisoara',
        img1: part1,
        img2: part2,
        cifra1: 0,
        cifra2: 1,
        locMeci: 'Acasa',
        tipcampionat: 'Divizia A2 Vest',

    },
    {
        Runda : 2,
        DataMeci: '20.11.2022',
        OraMeci: '10:00',
        NumeEchipa: 'Speranta Bucuresti',
        NumeEchipa2: 'Juventus Timisoara',
        img1: part1,
        img2: part2,
        cifra1: 0,
        cifra2: 1,
        locMeci: 'Acasa ',
        tipcampionat: 'Divizia A2 Est',

    },
    {
        Runda : 3,
        DataMeci: '20.11.2022',
        OraMeci: '10:00',
        NumeEchipa: 'Speranta Bucuresti',
        NumeEchipa2: 'Juventus Timisoara',
        img1: part1,
        img2: part2,
        cifra1: 0,
        cifra2: 1,
        locMeci: 'Acasa ',
        tipcampionat: 'Divizia Juniori',

    },
    {
        Runda : 1,
        DataMeci: '20.11.2022',
        OraMeci: '10:00',
        NumeEchipa: 'Speranta Bucuresti',
        NumeEchipa2: 'Juventus Timisoara',
        img1: part1,
        img2: part2,
        cifra1: 0,
        cifra2: 1,
        locMeci: 'Acasa',
        tipcampionat: 'Divizia Cadeti',

    },
    {
        Runda : 2,
        DataMeci: '20.11.2022',
        OraMeci: '10:00',
        NumeEchipa: 'Speranta Bucuresti',
        NumeEchipa2: 'Juventus Timisoara',
        img1: part1,
        img2: part2,
        cifra1: 0,
        cifra2: 1,
        locMeci: 'Acasa ',
        tipcampionat: 'Divizia Sperante',

    },
    {
        Runda : 3,
        DataMeci: '20.11.2022',
        OraMeci: '10:00',
        NumeEchipa: 'Speranta Bucuresti',
        NumeEchipa2: 'Juventus Timisoara',
        img1: part1,
        img2: part2,
        cifra1: 0,
        cifra2: 1,
        locMeci: 'Acasa ',
        tipcampionat: 'DiviziaMinivolei',

    },
    {
        Runda : 1,
        DataMeci: '20.11.2022',
        OraMeci: '10:00',
        NumeEchipa: 'Speranta Bucuresti',
        NumeEchipa2: 'Juventus Timisoara',
        img1: part1,
        img2: part2,
        cifra1: 0,
        cifra2: 1,
        locMeci: 'Acasa',

    },
    {
        Runda : 2,
        DataMeci: '20.11.2022',
        OraMeci: '10:00',
        NumeEchipa: 'Speranta Bucuresti',
        NumeEchipa2: 'Juventus Timisoara',
        img1: part1,
        img2: part2,
        cifra1: 0,
        cifra2: 1,
        locMeci: 'Acasa ',

    },
    {
        Runda : 3,
        DataMeci: '20.11.2022',
        OraMeci: '10:00',
        NumeEchipa: 'Speranta Bucuresti',
        NumeEchipa2: 'Juventus Timisoara',
        img1: part1,
        img2: part2,
        cifra1: 0,
        cifra2: 1,
        locMeci: 'Acasa ',

    },
    {
        Runda : 1,
        DataMeci: '20.11.2022',
        OraMeci: '10:00',
        NumeEchipa: 'Speranta Bucuresti',
        NumeEchipa2: 'Juventus Timisoara',
        img1: part1,
        img2: part2,
        cifra1: 0,
        cifra2: 1,
        locMeci: 'Acasa',

    },
    {
        Runda : 2,
        DataMeci: '20.11.2022',
        OraMeci: '10:00',
        NumeEchipa: 'Speranta Bucuresti',
        NumeEchipa2: 'Juventus Timisoara',
        img1: part1,
        img2: part2,
        cifra1: 0,
        cifra2: 1,
        locMeci: 'Acasa ',

    },
    {
        Runda : 3,
        DataMeci: '20.11.2022',
        OraMeci: '10:00',
        NumeEchipa: 'Speranta Bucuresti',
        NumeEchipa2: 'Juventus Timisoara',
        img1: part1,
        img2: part2,
        cifra1: 0,
        cifra2: 1,
        locMeci: 'Acasa ',

    },
    {
        Runda : 1,
        DataMeci: '20.11.2022',
        OraMeci: '10:00',
        NumeEchipa: 'Speranta Bucuresti',
        NumeEchipa2: 'Juventus Timisoara',
        img1: part1,
        img2: part2,
        cifra1: 0,
        cifra2: 1,
        locMeci: 'Acasa',

    },
    {
        Runda : 2,
        DataMeci: '20.11.2022',
        OraMeci: '10:00',
        NumeEchipa: 'Speranta Bucuresti',
        NumeEchipa2: 'Juventus Timisoara',
        img1: part1,
        img2: part2,
        cifra1: 0,
        cifra2: 1,
        locMeci: 'Acasa ',

    },
    {
        Runda : 3,
        DataMeci: '20.11.2022',
        OraMeci: '10:00',
        NumeEchipa: 'Speranta Bucuresti',
        NumeEchipa2: 'Juventus Timisoara',
        img1: part1,
        img2: part2,
        cifra1: 0,
        cifra2: 1,
        locMeci: 'Acasa ',

    },
    {
        Runda : 1,
        DataMeci: '20.11.2022',
        OraMeci: '10:00',
        NumeEchipa: 'Speranta Bucuresti',
        NumeEchipa2: 'Juventus Timisoara',
        img1: part1,
        img2: part2,
        cifra1: 0,
        cifra2: 1,
        locMeci: 'Acasa',

    },
    {
        Runda : 2,
        DataMeci: '20.11.2022',
        OraMeci: '10:00',
        NumeEchipa: 'Speranta Bucuresti',
        NumeEchipa2: 'Juventus Timisoara',
        img1: part1,
        img2: part2,
        cifra1: 0,
        cifra2: 1,
        locMeci: 'Acasa ',

    },
    {
        Runda : 3,
        DataMeci: '20.11.2022',
        OraMeci: '10:00',
        NumeEchipa: 'Speranta Bucuresti',
        NumeEchipa2: 'Juventus Timisoara',
        img1: part1,
        img2: part2,
        cifra1: 0,
        cifra2: 1,
        locMeci: 'Acasa ',

    },
    {
        Runda : 1,
        DataMeci: '20.11.2022',
        OraMeci: '10:00',
        NumeEchipa: 'Speranta Bucuresti',
        NumeEchipa2: 'Juventus Timisoara',
        img1: part1,
        img2: part2,
        cifra1: 0,
        cifra2: 1,
        locMeci: 'Acasa',

    },
    {
        Runda : 2,
        DataMeci: '20.11.2022',
        OraMeci: '10:00',
        NumeEchipa: 'Speranta Bucuresti',
        NumeEchipa2: 'Juventus Timisoara',
        img1: part1,
        img2: part2,
        cifra1: 0,
        cifra2: 1,
        locMeci: 'Acasa ',

    },
    {
        Runda : 3,
        DataMeci: '20.11.2022',
        OraMeci: '10:00',
        NumeEchipa: 'Speranta Bucuresti',
        NumeEchipa2: 'Juventus Timisoara',
        img1: part1,
        img2: part2,
        cifra1: 0,
        cifra2: 1,
        locMeci: 'Acasa ',

    },
    {
        Runda : 1,
        DataMeci: '20.11.2022',
        OraMeci: '10:00',
        NumeEchipa: 'Speranta Bucuresti',
        NumeEchipa2: 'Juventus Timisoara',
        img1: part1,
        img2: part2,
        cifra1: 0,
        cifra2: 1,
        locMeci: 'Acasa',
        

    },
    {
        Runda : 2,
        DataMeci: '20.11.2022',
        OraMeci: '10:00',
        NumeEchipa: 'Speranta Bucuresti',
        NumeEchipa2: 'Juventus Timisoara',
        img1: part1,
        img2: part2,
        cifra1: 0,
        cifra2: 1,
        locMeci: 'Acasa ',

    },
    {
        Runda : 3,
        DataMeci: '20.11.2022',
        OraMeci: '10:00',
        NumeEchipa: 'Speranta Bucuresti',
        NumeEchipa2: 'Juventus Timisoara',
        img1: part1,
        img2: part2,
        cifra1: 0,
        cifra2: 1,
        locMeci: 'Acasa ',

    },
    {
        Runda : 1,
        DataMeci: '20.11.2022',
        OraMeci: '10:00',
        NumeEchipa: 'Speranta Bucuresti',
        NumeEchipa2: 'Juventus Timisoara',
        img1: part1,
        img2: part2,
        cifra1: 0,
        cifra2: 1,
        locMeci: 'Acasa',

    },
    {
        Runda : 2,
        DataMeci: '20.11.2022',
        OraMeci: '10:00',
        NumeEchipa: 'Speranta Bucuresti',
        NumeEchipa2: 'Juventus Timisoara',
        img1: part1,
        img2: part2,
        cifra1: 0,
        cifra2: 1,
        locMeci: 'Acasa ',

    },
    {
        Runda : 3,
        DataMeci: '20.11.2022',
        OraMeci: '10:00',
        NumeEchipa: 'Speranta Bucuresti',
        NumeEchipa2: 'Juventus Timisoara',
        img1: part1,
        img2: part2,
        cifra1: 0,
        cifra2: 1,
        locMeci: 'Acasa ',

    },

];